### ISSUE TITLE
PostreSQL strange sequences names

### ISSUE THREAD

**Issue by slsxo** [wintercms/wn-blog-plugin#37]
### Winter CMS Build

1.2

### PHP Version

8.1

### Database engine

PostgreSQL

### Plugins installed

Winter.Blog

### Issue description

Well, if we have winter_blog_posts table, why sequence record should be named rainlab_blog_posts_id_seq instead of winter_blog_posts_id_seq? That's not a big deal, but can be an issue. 

### Steps to replicate

composer require wintercms/wn-blog-plugin &&
php artisan down &&
php artisan winter:up &&
php artisan cache:clear &&
php artisan up

**Comment by bennothommo** [comment]
@slsxo could you please post a screenshot or more info on what you're seeing? I assume the sequence records are to do with the indexes, but I don't have PostgreSQL available.

**Comment by slsxo** [comment]
![image](https://user-images.githubusercontent.com/104219168/229640087-384e685d-5562-446c-89fd-e209fc4b8913.png)

Let's say sequence is an AUTO_INCREMENT, but name matters.
Take a look at default value of the id column `[nextval('rainlab_blog_posts_id_seq')]`.
Conventional name format  `{ table_name }_{ column_name }_seq`.

**Comment by bennothommo** [comment]
@slsxo this is a guess, but it may be because our [version history and migrations](https://github.com/wintercms/wn-blog-plugin/blob/main/updates/v1.0.1/create_posts_table.php#L11) use the original RainLab tables to allow people to migrate their October sites to Winter. It's only when you reach v2.0.0 that it renames the tables and indexes to Winter.

What I imagine is happening here is because the table is originally created as `rainlab_blog_posts`, the auto-increment sequence is being created with that name, and that name persists even when the table is renamed. I would say it's likely it won't cause any issues, but if you would like, we'd be happy to accept a PR that renames the sequence for PostgreSQL.
